### ISSUE TITLE
Webpack issue with svg files

### ISSUE THREAD

**Issue by PatrickFranz** [OscarRobertRodriguez/developerNews#15]
Looks like Webpack might need a loader for SVG. 

Webpack error: 

ERROR in ./src/assets/images/Twitter_Logo_Blue.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

This is probably all we need: https://github.com/webpack-contrib/svg-inline-loader

I'll leave this for whomever is handling the tooling.

**Comment by Gruximillian** [comment]
Oh, I saw this morning that there was not svg matching pattern in webpack settgins, but since there was no svgs invloved I didn't change it. Look for this code in webpack.config.js file:

```
// look for all image types 
      {
        test: /.*\.(gif|png|jpe?g)$/i, 
        use: [
          {
            loader: 'url-loader',
            options: {
              // if images is less that 5kbs inline to reduce http request
              limit: 5000,
              // output path in the dist folder
              name: 'assets/images/[name].[ext]'
            }
          }
        ]
      },
```

And try to update the test line to: 
`test: /.*\.(svg|gif|png|jpe?g)$/i,`

Hope it works for you.
