### ISSUE TITLE
Button margin

### ISSUE THREAD

**Issue by PatrickFranz** [OscarRobertRodriguez/developerNews#48]
The .button class contains a margin which makes it hard to place precisely.

I think the placement of the component is better left to who ever is using it.

Thoughts?

**Comment by OscarRobertRodriguez** [comment]
Makes sense take the margins out  use flexbox to display buttons in  modal
--
Sent from Mail.Ru app for Android Monday, 22 January 2018, 03:49PM -06:00 from Patrick Franz  notifications@github.com :

**Comment by Gruximillian** [comment]
@OscarRobertRodriguez, @PatrickFranz 

Is this issue resolved?

**Comment by PatrickFranz** [comment]
Yes it is.
