### ISSUE TITLE
.blog section too narrow

### ISSUE THREAD

**Issue by PatrickFranz** [OscarRobertRodriguez/developerNews#49]
It looks like the main blog section is much more narrow than the mock-up we were given. This is having the effect of crowding elements within.

Looks like @OscarRobertRodriguez changed that yesterday (which is what caused the problems with the Twitter elements).

Should probably be set to look more like the mock-up.

**Comment by OscarRobertRodriguez** [comment]
Okay we'll make it wider
--
Sent from Mail.Ru app for Android Monday, 22 January 2018, 04:02PM -06:00 from Patrick Franz  notifications@github.com :

**Comment by Gruximillian** [comment]
@OscarRobertRodriguez, @PatrickFranz 
Is this resolved too?

**Comment by OscarRobertRodriguez** [comment]
Yes

**Comment by Gruximillian** [comment]
Ok, I'm closing the issue then.
